### ISSUE TITLE
mudrod-core pom error

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#10]
Error: 
Description Resource    Path    Location    Type
org.apache.maven.archiver.MavenArchiver.getManifest(org.apache.maven.project.MavenProject, org.apache.maven.archiver.MavenArchiveConfiguration) pom.xml /mudrod-core    line 1  Maven Configuration Problem

I am not familiar with Maven config, but I found a discussion here @lewismc : 
http://stackoverflow.com/questions/37555557/m2e-error-in-mavenarchiver-getmanifest

**Comment by lewismc** [comment]
Can you explain how and when this error arises? I am not able to reproduce it. Thanks @Yongyao

**Comment by lewismc** [comment]
@Yongyao PING

**Comment by lewismc** [comment]
@Yongyao is this still an issue? If not then please resolve.

**Comment by Yongyao** [comment]
It still exists on one of my local machine, but the program can run fine with this error. I will close this for now.
