### ISSUE TITLE
Dataset links don't work

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#101]
When the search results show up it is not possible to click on a link.

The links are invalid in dataset.js

Failed to load resource: the server responded with a status of 404 (Not Found)
https://mudrod.jpl.nasa.gov/mudrod-web/**SearchVocab**?concept=ocean+wind&operator=Phrase 

Failed to load resource: the server responded with a status of 404 (Not Found)
https://mudrod.jpl.nasa.gov/mudrod-web/**DatasetDetail**?shortname=QSCAT_LEVEL_2B_COMP_12 

Failed to load resource: the server responded with a status of 404 (Not Found)
https://mudrod.jpl.nasa.gov/mudrod-web/**HybirdRecomDatasets**?shortname=QSCAT_LEVEL_2B_COMP_12&operator=Phrase

**Comment by fgreg** [comment]
I fixed the links in the UI javascript but there is still more to do.

@Yongyao @lewismc This page is trying to call GET on HybridRecomDatasetsResource, RecomDatasetsResource, and SearchDatasetDetailResource but none of those methods exist. What is this page supposed to be doing?

**Comment by fgreg** [comment]
Not fixed yet.

**Comment by Yongyao** [comment]
@quintinali Could you please take a look at this? I am sure the code were there (written by you).

**Comment by quintinali** [comment]
@Yongyao @fgreg Did you encounter this problem? The search function doesn't work on my computer since it can't find AutoCompleteResource class. 
![image](https://cloud.githubusercontent.com/assets/8673393/23538647/bbddd470-ff89-11e6-945a-334354c7e4e0.png)

**Comment by Yongyao** [comment]
No, make sure you use the latest master branch

**Comment by lewismc** [comment]
Absolutely everyone needs to be working off of master branch from now on. I think this is where some of our problems stem from folks. We all need to be using master branch as this is where mainline development is going on, this is meant to be stable and this is what @fgreg is trying to deploy at JPL. 

We need to be working off of master branch, if we are not working off of master then we are simply wasting time.

**Comment by quintinali** [comment]
@fgreg I fixed the bug. Please update master code and try it. Please let me know if any problem, thanks.

**Comment by Yongyao** [comment]
It works for me now. I can see the MUDROD dataset landing page (not the PO.DAAC one).

**Comment by lewismc** [comment]
Please send pull requests for everything that way we can see what has changed. Thanks folks.
