### ISSUE TITLE
SearchDatasetDetailResource Missing GET method

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#102]
The `SearchDatasetDetailResource` does not have a GET method but the UI tries to call GET from `dataset.js`

@lewismc Can you take a look?

**Comment by quintinali** [comment]
@fgreg @lewismc  I fixed this problem. Pleased close this issue after reviewing. Thanks

**Comment by lewismc** [comment]
@quintinali what did you do to fix the issue? Can you reference it here please? Thank you.

**Comment by lewismc** [comment]
@quintinali what are we meant to be reviewing?

**Comment by lewismc** [comment]
I see no pull request.

**Comment by quintinali** [comment]
@lewismc Oh, my mistake. I encountered some problems to solve the issue in my repository so I directly modified code in the mudrod master and used the "sync" button to submit the code. I fixed this issue when I solved the issue https://github.com/mudrod/mudrod/issues/101. Please check this commit https://github.com/mudrod/mudrod/commit/85c9a0c8120e4e00f5886438f080cb866ab833cc

**Comment by lewismc** [comment]
OK thank you
