### ISSUE TITLE
WebUI Re-architecture

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#117]
This issue is a placeholder for the entire re-architecture of the MUDROD web module [0].

 * Current frontend codebase implemented in pure HTML/CSS/JS with no templating or framework design.
 * Current UI codebase can be found at https://github.com/mudrod/mudrod/tree/master/web, the code currently exists as a Maven module and is packaged as a Web Archive (WAR) which can be deployed in any J2EE Servlet container such as Apache Tomcat, Jetty, etc.
 * Codebase is in need of fresh re-architecture… proposed solution should include simple intuitive modern elements such as [AngularJS](https://angularjs.org/), HTML5, etc. which will interact with existing [REST services](https://github.com/mudrod/mudrod/tree/master/service/src/main/java/gov/nasa/jpl/mudrod/services).

If you were able to provide us with an overview of what the re-architecture would look like for Wednesday 29th March (this Wednesday) that would be great. If you are not familiar with AngularJS and would prefer to use another framework then please suggest one. At this stage we are open to reasonable suggestions as time is somewhat of an issue and we want you to work with tooling that you are comfortable with and efficient using.

Please write back here with all issues and submit pull requests as early and a frequently as possible. You can also catch us over on mudrod-all@jpl.nasa.gov

[0] https://github.com/mudrod/mudrod/tree/master/web

**Comment by fgreg** [comment]
Complete
