### ISSUE TITLE
Change how javaSVMWithSGDModel is loaded

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#119]
Should not have to modify config.xml to include an absolute file path to the `javaSVMWithSGDModel` directory.

At the very lest this directory should be able to be loaded as a classpath resource.

**Comment by Yongyao** [comment]
@fgreg , both Lewis and I spent some time on this a while ago. There would be an error if we put it in the resource folder. Looks like some content of the folder will change after the code is built. (the folder is a model generated by Spark MLlib)

Yeah, it definitely should be loaded as classpath resource. It would be great if you can figure this out.

**Comment by fgreg** [comment]
@Yongyao My plan is to do it like this:

1. During build, zip the directory and include it as a resource to the JAR
2. Modify `gov.nasa.jpl.mudrod.ssearch.ranking.Learner#Learner` to load the zip file as a classpath resource, extract it to a temporary directory
3. Provide the absolute path to the temporary directory to the spark context and SVM
