### ISSUE TITLE
MUDROD testing results

### ISSUE THREAD

**Issue by edshred2000** [mudrod/mudrod#122]
Results to report testing the JPL MUDROD web site

1. 'And' is perhaps the best default for free text keyword searches.  'Phrase' is too restrictive for longer keyword queries (e.g, 'coastal ocean wind') 
2. Keyword 'Altimetry' returns nothing.  'Altimeter' does. Ontology can help here ?
3. No link to dataset landing page in search results. Nowhere to navigate to a data access page.

**Comment by Yongyao** [comment]
@edshred2000 OK, we will fix this. If you or David find anything else, please also post it here.

**Comment by Yongyao** [comment]
@lewismc @fgreg Any comments on "Keyword 'Altimetry' returns nothing. 'Altimeter' does. Ontology can help here ?" I think it has to do with the stemming function. Maybe we need a domain-specific one here.

**Comment by Yongyao** [comment]
Comments 1 & 3 have been addressed in https://github.com/mudrod/mudrod/pull/123

**Comment by Yongyao** [comment]
David's comments are below.

1. Dataset indexing needs to be updated to include more up-to-date datasets; perhaps, this could be an automated cron job that runs once per week. 
2. For similar datasets with multiple versions, highest version number should be placed at higher ranking than older versions, regardless of differences in the existing user popularity.
3. Ensure search terms that are a direct match to a mission/platform/sensor of a given dataset will result in highest rank compared to a related dataset of a different mission/platform/sensor.
4. Abstract should include at least the first 150 characters (with option to expand to full description) of the Dataset Description.
5. The following additional geospatial metadata should be displayed in search results; alternatively, these could be incorporated into a “faceted” search mechanism in the side-bar.
Dataset start/stop date
Dataset spatial resolution
Dataset temporal resolution
Data Format
6. For the Topic, the term should be a hyperlink that points to existing Measurement information pages, such as:
Surface Winds, Wind Stress, Vorticity, Surface Winds, Convergence/Divergence, Sigma Naught > https://podaac.jpl.nasa.gov/OceanWind 
Ice Extent, Sea Ice Age > https://podaac.jpl.nasa.gov/SeaIce 
Ocean Currents > https://podaac.jpl.nasa.gov/OceanCurrentsCirculation

**Comment by fgreg** [comment]
@Yongyao can you break this into individual issues? I think some of these have been address while others have not.

**Comment by fgreg** [comment]
@Yongyao @lewismc Actually I think this might have been done already?

https://github.com/mudrod/mudrod/issues/140
https://github.com/mudrod/mudrod/issues/141
https://github.com/mudrod/mudrod/issues/142

If so, I'd say close this issue.

**Comment by Yongyao** [comment]
This is only one issue that remains to be solved. https://github.com/mudrod/mudrod/issues/152
