### ISSUE TITLE
Create adhoc ingestion wiki page

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#138]
@Yongyao @quintinali there seems to be some process that you have for harvesting metadata from the PO.DAAC Webservices API.
If this is true, can you create a wiki page detailing how this works, how the tool(s) are executed, what output is expected and how the output is loaded into MUDROD?
This ingestion task should be automated such that it initiates whenever a new dataset announcement is made.

**Comment by Yongyao** [comment]
This is done. https://github.com/mudrod/mudrod/wiki/Command-Line-Interface
