### ISSUE TITLE
Augment records with additional geospatial metadata

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#143]
The following additional geospatial metadata should be displayed in search results; alternatively, these could be incorporated into a “faceted” search mechanism in the side-bar.
Dataset start/stop date
Dataset spatial resolution
Dataset temporal resolution
Data Format

**Comment by Yongyao** [comment]
This has been fixed already. Although the date formate has a bit problem, that's another issue.
<img width="813" alt="screen shot 2017-05-02 at 3 31 03 pm" src="https://cloud.githubusercontent.com/assets/5552606/25635527/73951a00-2f4c-11e7-8b07-78a3590ed07e.png">
