### ISSUE TITLE
Implement topic hyperlinks

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#144]
For the Topic, the term should be a hyperlink that points to existing Measurement information pages, such as:
```
Surface Winds, Wind Stress, Vorticity, Surface Winds, Convergence/Divergence, Sigma Naught > https://podaac.jpl.nasa.gov/OceanWind 
Ice Extent, Sea Ice Age > https://podaac.jpl.nasa.gov/SeaIce 
Ocean Currents > https://podaac.jpl.nasa.gov/OceanCurrentsCirculation 
```

**Comment by fgreg** [comment]
This conflicts with https://github.com/mudrod/mudrod/issues/151

On the call today it was suggested to make the value of 'Topic' be a hyperlink to a MUDROD search for that term.

Decision is needed as to which approach should be taken.

**Comment by gxtchen** [comment]
Some topic has use comma as separator and some uses / as separator, does javascript support string split with multiple separators?

**Comment by lewismc** [comment]
Hi @gxtchen please check out [this thread](http://stackoverflow.com/questions/650022/how-do-i-split-a-string-with-multiple-separators-in-javascript#650037), it should do the trick :)

**Comment by fgreg** [comment]
Decided during meeting today that this issue should be closed in favor of https://github.com/mudrod/mudrod/issues/151
