### ISSUE TITLE
Order of search result details

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#148]
After clicking on a dataset after search, the elements of the dataset detail should be updated

1. Long Name
2. Dataset Landing Page

Next should be the four terms:

- Category
- Topic
- Term
- Variable

The order of these terms should match the GMCD hierarchy for these terms.

Then the rest of the attributes.

**Comment by Yongyao** [comment]
Please refer to this PR https://github.com/mudrod/mudrod/pull/154
