### ISSUE TITLE
Dates need to follow ISO 8601 format 

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#150]
All dates being displayed need to be in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.

There is a bug in TimeSpan on dataset detail page but all dates need to be checked to make sure they meet the standard.

**Comment by edshred2000** [comment]
An example format would be

2005-06-01 representing June 1, 2005

**Comment by quintinali** [comment]
@Yongyao  I think I should modify dates format on the rearchitected WebUI. Will do it after testing the latest UI.

**Comment by fgreg** [comment]
Complete.
