### ISSUE TITLE
query and search operator should remain in the search bar when a query is executed

### ISSUE THREAD

**Issue by quintinali** [mudrod/mudrod#189]
1. Search Operator options disappear when a query is executed from index.html, the Operators re-appear when the autocomplete option is selected.
2. query should remain in the search bar in dataset results page.

**Comment by quintinali** [comment]
@fgreg Could you please tell me which branch should I use to improve web UI, master branch, https://github.com/mudrod/mudrod/tree/mudrod-117 or any other branch? Thanks.

**Comment by fgreg** [comment]
@quintinali For these fixes, use the mudrod-117 branch. Thanks.

**Comment by fgreg** [comment]
@quintinali I merged the PR 191 but I just noticed a regression that was introduced.

Now the Search options no longer disappear, but they get "pushed down" when the autocomplete form shows up:

![image](https://user-images.githubusercontent.com/1487133/26844593-cbdd2622-4aa8-11e7-9ae6-bf8568ece2c5.png)

**Comment by quintinali** [comment]
@fgreg  the searcher operator will return to the original position after finishing autocompletion. Do you want the operators are hidden behind the autocompletion list?

**Comment by fgreg** [comment]
@quintinali Yes I think that would be better. It's weird having them jump all over the place as the size of the suggestion list changes.

**Comment by quintinali** [comment]
@fgreg Ok, I will open a new issue to fix it. Thanks.

**Comment by fgreg** [comment]
Fixed with PR https://github.com/mudrod/mudrod/pull/198
