### ISSUE TITLE
Implement commons-cli for all Tool invocation and CLI logic

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#19]
The Commons Command Line Interface library is a very widely used implementation for all CLI logic.
https://commons.apache.org/proper/commons-cli/
I propose to use it for all Mudrod tools such that we can create better CLI code.

**Comment by Yongyao** [comment]
Agreed. Please let us know when you create a example. Changing "LogIngest" to the standard CLI could is good enough. Thanks. @lewismc

**Comment by lewismc** [comment]
@Yongyao pull request coming up shortly.
