### ISSUE TITLE
improve MUDROD dataset landing page

### ISSUE THREAD

**Issue by quintinali** [mudrod/mudrod#190]
1. change terminology of Start/End Date: from $start date - Present (instead of now)
2.  the Format should be changed from RAW to BINARY
3. units should be changed from ‘m’ to ‘km’
4. coverage language needs to reflect that currently on the PO.DAAC Website
5. Doi should be DOI, the link should also be linkable e.g. hyperlink

**Comment by fgreg** [comment]
@quintinali Use mudrod-117 branch for this as well.
