### ISSUE TITLE
a hover-over for all ranking scores is needed in the related searches panel 

### ISSUE THREAD

**Issue by quintinali** [mudrod/mudrod#193]
_1. Hide ranking scores in the search panel_
2. Add a separated page describing the ranking methodology/recommendation methodology on mudrod.github.io site.
3. Add links to the mudrod.github.io pages at the bottom of the right-hand side recommendation widget

@lewismc @fgreg  Could you please check out the above description to confirm it meets the requirement? Thanks

**Comment by lewismc** [comment]
@quintinali can you show me where the following is implemented?
```Hide ranking scores in the search panel```

**Comment by quintinali** [comment]
@lewismc Is it necessary to hide those scores assigned to related queries?

![image](https://cloud.githubusercontent.com/assets/8673393/26742896/81461de2-4794-11e7-8717-7a2960a9ea42.png)

**Comment by lewismc** [comment]
No, please retain the scores, but put a link at the bottom with a link to the page on mudrod.github.io

**Comment by quintinali** [comment]
Ok, thanks. I will remove the first item in the description.

**Comment by gxtchen** [comment]
Do you meant to have a link on the last item in "Related Search Panel" to open a new tab to  "mudrod.github.io"?

**Comment by quintinali** [comment]
I think we should add another item such as "vocabulary similarity algorithm" and  "recommendation algorithm" to link to mudrod.github.io pages. @lewismc How do you think about it? Thanks.

**Comment by lewismc** [comment]
Yes, something like "Click here for a description of our ranking algorithm(s)." this should open a new tab, NOT navigate the user away from the WebUI.

**Comment by quintinali** [comment]
@gxtchen  Could you please add these links at the right panel after changing it to side-by-side tabs
(row 11 in spreadsheet: when you click on a dataset landing page, the two tabs denoting ‘Related datasets’ and ‘Related Searches’ should be side-by-side tabs instead of underneath)

link to related keyword searches algorithm: https://mudrod.github.io/vocabulary-similarity-algorithm/
link to Related datasets algorithm: https://mudrod.github.io/recommendation-algorithms/

**Comment by fgreg** [comment]
Complete https://github.com/mudrod/mudrod/pull/206/commits/8bb5ca69171b3a083a23a26ceb67d0c5602bb108
