### ISSUE TITLE
Provide SORT BY functionality for facet-based query refinement

### ISSUE THREAD

**Issue by quintinali** [mudrod/mudrod#194]
Provide sort by function as shown in the following image
![image](https://cloud.githubusercontent.com/assets/8673393/26742576/15f2a0de-4793-11e7-85c0-600f659c6284.png)

1. long name (a-z)
2 short name(a-z)
3. grid spatial resolution
4. satellite spatial resolution
5. start date
6. stop date

@lewismc Could you please check above description to confirm it meets the requirement? Thanks

**Comment by lewismc** [comment]
It sounds good to me.

**Comment by fgreg** [comment]
@quintinali I saw your note on the PR that this requires metadata to be re-indexed. You mean running mudrod-engine with the -m flag correct?

I am now getting this error locally when running a search:

`Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [Dataset-ShortName] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.
`

This is after running mudrod-engine with -m flag.

**Comment by quintinali** [comment]
@fgreg  with -m flag,  just data in the metadata type are deleted.  The metadata mapping is not changed. I deleted the "mudrod" index and reingested metadata. But weblog procss result will also be deleted during this process.  So after deleting the "mudrod" index, I also run process() in the WeblogDiscoveryEngine.java file.

https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-delete-mapping.html

**Comment by fgreg** [comment]
@quintinali What are the consequences of deleting the weblog process result? 

I'm trying to avoid having to do a full re-ingestion. So I delete `mudrod` index then run `mudrod-engine` with -m? is that right?

**Comment by quintinali** [comment]
Deleting the weblog process result means word similarity results are deleted, so the right panel can not provide related search keywords.

@fgreg 

1. delete mudrod index
2. run mudrod-engine -m to ingest metadata
3. comment out "wd.preprocess();" in startLogIngest() function  in MudrodEngine.java
4. run mudrod-engine -l to process web logs
5. remove comment to wd.preprocess().

Through above steps, you can avoid a full re-ingestion. It is a little complicated since we don't have a flag just processing the weblogs.

**Comment by fgreg** [comment]
@quintinali We have 8 months of logs now, so I would have to do this for all 8 months?

I can't comment out code in the production (or UAT) deployment.

**Comment by quintinali** [comment]
@fgreg monthly logs are stored in different indexes rather than the "mudrod" index. For example, podaaclog201611.w5.gz log is stored in "podaaclog201611.w5.gz". Deleting "mudrod" index will only delete log processing results not the original logs.

I think we have two choices.
(1) add a separated command to process web logs. Processing logs ( calculate user history and click stream data) is much quicker than preprocessing logs ( ingest log and construct sessions). It will not take long to process 8 months of logs.

(2) add a custom function to update metadata mapping(I am not sure whether it works for Elasticsearch 5.0). 
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#updating-field-mappings
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-delete-mapping.html

Which one do you prefer to? Should we try solution 2 at first?

**Comment by quintinali** [comment]
@fgreg For the autocompletion part, @lewismc also changed metadata mapping. @lewismc Do you have any suggestion to solve above issue?

**Comment by fgreg** [comment]
@quintinali What is it we're trying to change exactly? If I query my local index:

http://127.0.0.1:9200/mudrod/_mapping/RawMetadata

I see:

```
"RawMetadata": {
  "dynamic_templates": [
    {
      "strings": {
        "match_mapping_type": "string",
        "mapping": {
          "analyzer": "english",
          "fielddata": true,
          "fields": {
            "raw": {
              "type": "string",
              "index": "not_analyzed"
            }
          },
        "type": "text"
        }
      }
    }
```

Isn't the `"fielddata": true,` what we're looking for? What else needs to get updated?

**Comment by quintinali** [comment]
@fgreg updates include:
(1) "fielddata": true
(2) "fields": {
            "raw": {
              "type": "string",
              "index": "not_analyzed"
            }
          }

**Comment by fgreg** [comment]
@quintinali So what I have right now should work? Is my error related to something introduced by @lewismc ?

**Comment by quintinali** [comment]
@fgreg I don't think so. Could you please check the mapping of Dataset-ShortName field in RawMetadata? I think it is not updated.

What you posted is the "dynamic_templates". Those updates should be applied to every field in the RawMetadata type.

**Comment by fgreg** [comment]
@quintinali Correct, "Dataset-Shortname" does not show `"fielddata": true`. Right now it is:

```
"Dataset-ShortName": {
  "type": "text",
  "analyzer": "english"
},
```

What should it be? If I understand correctly, it should be:

```
"Dataset-ShortName": {
  "type": "text",
  "fielddata": true,
  "analyzer": "english"
  "fields": {
    "raw": {
      "type": "string",
      "index": "not_analyzed"
     }
  },
},
```

**Comment by quintinali** [comment]
@fgreg Form my side, the mapping is:
"Dataset-ShortName": {
                  "type": "text",
                  "analyzer": "english",
                  "fielddata": true
 }

**Comment by quintinali** [comment]
@fgreg  I'm very sorry. What I just posted is wrong. The mapping queried from sense is as following:

"Dataset-ShortName": {
                  "type": "text",
                  "fields": {
                     "raw": {
                        "type": "keyword"
                     }
                  },
                  "analyzer": "english",
                  "fielddata": true
               },

**Comment by fgreg** [comment]
@quintinali I was able to update the mapping directly using a `PUT` request and it seems to work now:

```
curl 'http://127.0.0.1:9200/mudrod/_mapping/RawMetadata?update_all_types' -X PUT -H 'Pragma: no-cache' -H 'Origin: http://127.0.0.1:9100' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'Referer: http://127.0.0.1:9100/' -H 'Connection: keep-alive' --data '{"properties":{"Dataset-ShortName":{"type":"text","fielddata":true,"analyzer":"english","fields":{"raw":{"type":"string","index":"not_analyzed"}}}}}' --compressed
```

Do I need to do this to all fields that have only `"type": "text"` and `"analyzer": "english"` currently? Or is updating the `Dataset-ShortName` good enough?

**Comment by quintinali** [comment]
@fgreg 

(1) "fielddata": true is used to enable sort function for a field. Thus this mapping should be added to all fields related to "sort by function" shown in https://github.com/mudrod/mudrod/pull/204/files#diff-9589b36f921018b8701d9c6841682406R118
(2) "fields": {"raw": {"type": "keyword"}} is used to enable sort by A-Z function on  Dataset-ShortName and  Dataset-LongName fields.
(3) To simplify the template, I added these two mapping to most fields. You can decide by yourself, but only updating Dataset-ShortName is not enough.

**Comment by fgreg** [comment]
@quintinali The other sort-by properties are all either long or float type and do not support `fielddata = true`.

I think the only mappings that need to be updated are `Dataset-ShortName` and `Dataset-LongName`

I ran these two commands to update the mappings in my index. This should be reproducible in UAT and PROD:

```
curl 'http://127.0.0.1:9200/mudrod/_mapping/RawMetadata?update_all_types' -X PUT -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript, */*; q=0.01' --data '{"properties":{"Dataset-ShortName":{"type":"text","fielddata":true,"analyzer":"english","fields":{"raw":{"type":"keyword","index":"not_analyzed"}}}}}' --compressed
curl 'http://127.0.0.1:9200/mudrod/_mapping/RawMetadata?update_all_types' -X PUT -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript, */*; q=0.01' --data '{"properties":{"Dataset-LongName":{"type":"text","fielddata":true,"analyzer":"english","fields":{"raw":{"type":"keyword","index":"not_analyzed"}}}}}' --compressed
```

**Comment by quintinali** [comment]
@fgreg Thanks for providing the solution for updating metadata mapping. Please let me know if any other problem.
