### ISSUE TITLE
Potential mistake in ClickstreamAnalyzer

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#21]
I found this probably is a mistake. 
@quintinali Can you check on this? Is the highlighted code supposed to be config.get("clickstreamSVDMatrix_tmp")

SVDAnalyzer svd = new SVDAnalyzer(config, es, spark);
      svd.GetSVDMatrix(config.get("clickstreamMatrix"),
          Integer.parseInt(config.get("clickstreamSVDDimension")),
          config.get("clickstreamSVDMatrix_tmp"));
      List<LinkageTriple> tripleList = svd
          .CalTermSimfromMatrix(**config.get("clickstreamMatrix")**);
      svd.SaveToES(tripleList, config.get("indexName"),
          config.get("clickStreamLinkageType"));

**Comment by quintinali** [comment]
Yes,  it should be clickstreamSVDMatrix_tmp. I will fix this bug.
