### ISSUE TITLE
Add Logo of GMU center at the banner

### ISSUE THREAD

**Issue by quintinali** [mudrod/mudrod#210]
@lewismc @fgreg I attended the ESTF meeting this week and showed the mudrod website mudrod.jpl.nasa.gov to Prof.Yang. He want us to add the GMU center logo (stccenter.net/stc) at the top banner

**Comment by fgreg** [comment]
@quintinali Do you have a hi-res image of the logo you are talking about?

Also, which top banner are you referring to? Next to the NASA Logo? That top banner is required by JPL policy for *.jpl.nasa.gov websites so I don't know if we can alter it; but I can find out.

**Comment by fgreg** [comment]
@quintinali I looked at the policy again and it seems there won't be an issue with an extra logo.

**Comment by quintinali** [comment]
@fgreg Thanks. I am on my way back home from the meeting. I will send the
high  resolution logo to you as soon as I get it.

**Comment by quintinali** [comment]
@fgreg  Attache is the logo of STC center. Please let me know if any problem.
![stc_logo](https://user-images.githubusercontent.com/8673393/27165124-cedd3976-5146-11e7-926c-6daed0e4c31b.png)

**Comment by freg** [comment]
Hi,
I'm not fgreg, i'm freg !
You have to verify the address of your dest...
Regards,
François

2017-06-15 0:17 GMT-04:00 quintinali <notifications@github.com>:

**Comment by fgreg** [comment]
@quintinali Do you have one where the background is transparent?

**Comment by quintinali** [comment]
@fgreg Attached is the logo with a transparent background. Please use this one. Thanks.
![stcenter_logo](https://user-images.githubusercontent.com/8673393/27235706-b04e4ac8-5276-11e7-90aa-5dc1bfe16fae.png)
