### ISSUE TITLE
Error when importing PD data in Mudrod 

### ISSUE THREAD

**Issue by clarkgogogo** [mudrod/mudrod#216]
We installed Mudrod and ElasticSearch 5.2.2 in CentOS 7.  Now we are trying to import PD test data into Mudrod system, so we generated 37583 metadata json files from ElasticSearch (this process is in my own Mac computer).  Then these Json files were copied to the CentOS virtual machine which has Mudrod and ElasticSearch installed.  

When trying to run the following command:
./core/target/appassembler/bin/mudrod-engine  -dataDir /home/centos/mudrod/PDdata -f
Errors come out:

ERROR main.MudrodEngine (MudrodEngine.java:main(411)) - Error whilst parsing command line.
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3118 path $

The complete error messages are in pictures below.
![screen shot 2018-03-06 at 1 52 29 pm](https://user-images.githubusercontent.com/14652024/37052966-e95ce008-2148-11e8-95b1-a7b7471ee892.png)
![screen shot 2018-03-06 at 1 53 12 pm](https://user-images.githubusercontent.com/14652024/37052969-ed097a2c-2148-11e8-8202-20aca95d5a51.png)

**Comment by lewismc** [comment]
hi @clarkgogogo as explained in the [README](https://github.com/aist-oceanworks/mudrod/blob/master/README.md) the project has moved to Apache under the [incubator-sdap-mudrod](https://github.com/apache/incubator-sdap-mudrod) project. If you have issues, please submit them there. Thanks.
