### ISSUE TITLE
Command line execution error

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#25]
@lewismc In case you missed the issue in pull request. This is the command I use: -l -logDir C:\mudrodLogIngest

ERROR main.MudrodEngine              - MudrodEngine: 'logDir' argument is mandatory. User must also provide either 'logIngest' or 'fullIngest'.
java.lang.NullPointerException
    at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:213)

Am I doing it wrong?

**Comment by lewismc** [comment]
Yes you are.
You should be executing exactly what is says

```
--logDir C:\mudrodLogIngest --logIngest
```

Please try that and then reply back here if it works. 
Thanks @Yongyao

**Comment by Yongyao** [comment]
@lewismc Still doesn't work. 

ERROR main.MudrodEngine              - MudrodEngine: 'logDir' argument is mandatory. User must also provide either 'logIngest' or 'fullIngest'.
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --logDir

I also tried --logIngest --logDir C:\mudrodLogIngest, and -l -logIngest -logDir C:\mudrodLogIngest

Neither of them work.

**Comment by lewismc** [comment]
@Yongyao please look at the command line options which you are provided with
When I execute

```
$MUDROD_HOME/core/target/appassembler/bin/mudrod
```

or for you on Windows

```
$MUDROD_HOME\core\target\appassembler\bin\mudrod.bat
```

You are provided with

```
usage: MudrodEngine: 'logDir' argument is mandatory. User must also
       provide either 'logIngest' or 'fullIngest'. [-f] [-h] [-l] -logDir
       <logDir>
 -f,--fullIngest    begin full ingest Mudrod workflow
 -h,--help          show this help message
 -l,--logIngest     begin log ingest with the WeblogDiscoveryEngine only
 -logDir <logDir>   the log directory to be processed by Mudrod
ERROR main.MudrodEngine              - MudrodEngine: 'logDir' argument is mandatory. User must also provide either 'logIngest' or 'fullIngest'.
org.apache.commons.cli.MissingOptionException: Missing required option: logDir
    at org.apache.commons.cli.DefaultParser.checkRequiredOptions(DefaultParser.java:199)
    at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:130)
    at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
    at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
    at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:194)
```

Please look at the command line options I am now providing

```
$MUDROD_HOME/core/target/appassembler/bin/mudrod -logDir /usr/local/mudrod/bin/ -l
```

The above command line invocation would
a) begin log ingest with the WeblogDiscoveryEngine only, and 
b) provide the log path on the local file system
This currently works for me no problem using master branch

Please look at invoking the same parameters using your local machine. Write back here with your issues.

Thanks

**Comment by Yongyao** [comment]
Yes, I tried to debug with exactly the same command line you provided.
`-logDir /usr/local/mudrod/bin/ -l`
But the processingType is always null after the following code.

```
      String processingType;
      if (line.hasOption(LOG_INGEST)) {
        processingType = line.getOptionValue(LOG_INGEST);
      } else {
        processingType = line.getOptionValue(FULL_INGEST);
      }
      String dataDir = line.getOptionValue(LOG_DIR).replace("\\", "/");
```

line.hasOption(LOG_INGEST) is true. line.getOptionValue(LOG_INGEST) returns null.

**Comment by lewismc** [comment]
@Yongyao please see #28

**Comment by lewismc** [comment]
Closing as this appears to have been resolved
