### ISSUE TITLE
Refactor, document and reformat ImportLogFile.java

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#26]
Right now the [InportLogFile.java](https://github.com/mudrod/mudrod/blob/master/core/src/main/java/esiptestbed/mudrod/weblog/pre/ImportLogFile.java) is a bit of a mess in terms of use of efficient data structures, documentation and general presentation.
PR coming up to solve this.

**Comment by Yongyao** [comment]
OK, I saw you have made a few changes to this file. I will continue to work on it.
