### ISSUE TITLE
Size of binary file stored in java resource folder gets changed in target

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#36]
@lewismc I am trying to load the ML classifier model, which is a binary file, from resource folder, but it gives me an reading error. After looking into it, I found the size gets changed after maven build. 

java.io.StreamCorruptedException: invalid stream header: EFBFBDEF
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at weka.core.SerializationHelper.read(SerializationHelper.java:275)
    at weka.core.SerializationHelper.read(SerializationHelper.java:257)
    at esiptestbed.mudrod.ssearch.ranking.Learner.<init>(Learner.java:45)
    at esiptestbed.mudrod.ssearch.Ranker.<init>(Ranker.java:46)
    at esiptestbed.mudrod.ssearch.Searcher.main(Searcher.java:332)

It looks like an maven problem from this thread: http://stackoverflow.com/questions/19500458/maven-resource-binary-changes-file-size-after-build

I tried a few solution I found online, but all of them would lead to some other maven error. Can you help me fix it? If need, I can send the binary file to you. Thanks.

**Comment by lewismc** [comment]
Please send me the binary file.

**Comment by Yongyao** [comment]
Btw, this is code used to load it.

```
        URL clsURL = Learner.class.getClassLoader().getResource("rankSVMmodel_new.model");
        File file = new File(clsURL.toURI());
        String clspath = file.getAbsolutePath();       
        cls = (Classifier) weka.core.SerializationHelper.read(clspath);
```

**Comment by lewismc** [comment]
Thats fine.

**Comment by Yongyao** [comment]
I have replace weka with Spark Mlib SVM module, but the problem still exists.

**Comment by lewismc** [comment]
@Yongyao look at the following, when I find the size of the model file

```
lmcgibbn@LMC-032857 /usr/local/mudrod/core/src/main/resources(temp0907) $ ls -al
total 32
drwxr-xr-x  7 lmcgibbn  admin   238 Sep 15 21:14 .
drwxr-xr-x  5 lmcgibbn  admin   170 Jul 13 16:31 ..
-rw-r--r--  1 lmcgibbn  admin  2728 Sep 15 13:49 config.xml
-rw-r--r--  1 lmcgibbn  admin  1175 Aug 25 20:33 elastic_mappings.json
-rw-r--r--  1 lmcgibbn  admin   633 Aug 25 20:33 elastic_settings.json
drwxr-xr-x  4 lmcgibbn  admin   136 Sep 15 13:49 javaSVMWithSGDModel
-rw-r--r--  1 lmcgibbn  admin  2710 Aug 25 20:33 log4j.properties
```

then when I build the project I see that the file size is the exact same

```
lmcgibbn@LMC-032857 /usr/local/mudrod/core/target/classes(temp0907) $ ls -al
total 32
drwxr-xr-x   8 lmcgibbn  admin   272 Sep 15 21:15 .
drwxr-xr-x  12 lmcgibbn  admin   408 Sep 15 21:15 ..
-rw-r--r--   1 lmcgibbn  admin  2728 Sep 15 21:15 config.xml
-rw-r--r--   1 lmcgibbn  admin  1175 Sep 15 21:15 elastic_mappings.json
-rw-r--r--   1 lmcgibbn  admin   633 Sep 15 21:15 elastic_settings.json
drwxr-xr-x   3 lmcgibbn  admin   102 Sep 15 21:15 esiptestbed
drwxr-xr-x   4 lmcgibbn  admin   136 Sep 15 21:15 javaSVMWithSGDModel
-rw-r--r--   1 lmcgibbn  admin  2710 Sep 15 21:15 log4j.properties
```

The size remains at 136 bytes... which is extremely small. Are you sure this is the correct file?

**Comment by Yongyao** [comment]
The real problem is, if I store the model on a local path, it can be read (in learner. Java constructor method). But there would be an error, when storing in under resource folder. Btw, the model should be a folder, not just a file.

**Comment by lewismc** [comment]
The model is a folder called `javaSVMWithSGDModel` containing both 

```
lmcgibbn@LMC-032857 /usr/local/mudrod_resources/RankingModel/javaSVMWithSGDModel $ ls -al
total 0
drwxr-xr-x@  4 lmcgibbn  staff  136 Sep  3 12:38 .
drwxr-xr-x@  3 lmcgibbn  staff  102 Sep  5 10:15 ..
drwxr-xr-x@ 10 lmcgibbn  staff  340 Sep  3 12:38 data
drwxr-xr-x@  6 lmcgibbn  staff  204 Sep  3 12:38 metadata
```

**Comment by quintinali** [comment]
@lewismc, when Yongyao put the RankingModel  under the resources directory, and load the model in the Learner.java using relative path, Mudrod doesn't work when it is started as a web service.

**Comment by lewismc** [comment]
OK thanks I am investigating.

**Comment by lewismc** [comment]
@Yongyao is this an issue anymore?

**Comment by Yongyao** [comment]
Yes, it's still a issue when we put the ranking model folder inside the Resource folder. But if we are good with storing the ranking model folder on a fixed local path, we are fine

**Comment by lewismc** [comment]
Can you please point me to an example 'ranking model folder'?

**Comment by Yongyao** [comment]
https://github.com/mudrod/mudrod/tree/master/core/src/main/resources/javaSVMWithSGDModel

Here it is.

**Comment by lewismc** [comment]
This is read in the following property 
https://github.com/mudrod/mudrod/blob/master/core/src/main/resources/config.xml#L70
It is used at runtime at the following code
https://github.com/mudrod/mudrod/blob/682320adfa549d81b62c26482f8e8ee490d93441/core/src/main/java/esiptestbed/mudrod/ssearch/ranking/Learner.java#L43
I think that this issue can be closed off. As long as the location of the resource is defined correctly within config.xml, everything is good.
