### ISSUE TITLE
Add comments_yun

### ISSUE THREAD

**Issue by quintinali** [mudrod/mudrod#38]
add comments for utils, semantics, metadata, web logs

**Comment by quintinali** [comment]
@lewismc I followed this guide(https://github.com/mudrod/mudrod/wiki/Mudrod-Development-Workflow)  to create a new branch and finish step 8. It seems that I still directly commit to master. Could you please check it when you have time?

**Comment by lewismc** [comment]
Did you send your pull request?

**Comment by quintinali** [comment]
I did not send pull request yet

**Comment by lewismc** [comment]
Well send the pull request e.g. in "Creating Pull Request" progress to Number 10. Once that is done you should be able to open a pull request.

**Comment by quintinali** [comment]
@lewismc I can not find the new branch named "MUDROD-addcomment-yun" in github web page, however, I can find it in my github desktop tool.  Can I pull  request from "MUDROD-addcomment-yun" into master from git hub desktop tool?

**Comment by lewismc** [comment]
If you are using the Github Desktop application please see
https://help.github.com/desktop/guides/contributing/sending-a-pull-request/
Thanks

**Comment by quintinali** [comment]
@lewismc It seems that the pull request is automatically merged to the master, which is commit 6425a2f955353b8fcb2c8d85987dc9458f51f73e. Am I right?  If the branch is  automatically merged to the master, how can we check the format of code and make sure the continuous integration test successful before merging branch into master?

**Comment by lewismc** [comment]
> @lewismc It seems that the pull request is automatically merged to the master, which is commit 6425a2f. Am I right?

You are not creating branches correctly. Please read the link I posted above. You will need to learn this as it is important in using a source code management platform like Github. Thanks.

**Comment by quintinali** [comment]
@lewismc  Thanks for your help. I will recreate a branch according to the guild later. Since I have directly submitted code to the master, do I need to reverse the commit in the master?

**Comment by lewismc** [comment]
Not for the time being it is OK. Please create branches in the future so we can all review. Thank you
