### ISSUE TITLE
Unpredictable shutdown of MUDROD web service

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#54]
Right now, we are working on this branch, which is the only branch that has ranking and recommendation functions. https://github.com/mudrod/mudrod/tree/temp0907
After service is started, it works well in the beginning, but automatically shuts down after 2~4 hours. No error log is found either in jetty log or mudrod.log.

Just to let you know, in the servlet web listener, we started one ES transport client and one spark driver. I guess this is might be something about memory leak. So the solution I come up with is to modify JVM heap memory size when starting jetty. (not tested yet)

 export MAVEN_OPTS="-Xmx2048m -Xms2048m" && mvn jetty:run

Do this make sense to you? BTW, if we copy mudrod.snapshot.war to tomcat webapp, it can be started.

**Comment by lewismc** [comment]
You should not use `mvn jetty:run` for any production box it is unstable and should be used for development only.

**Comment by lewismc** [comment]
This is described at https://github.com/mudrod/mudrod#deploying-to-apache-tomcat-or-any-other-servlet-container
If you have any issues running in Tomcat then let me know and we can reopen here.

**Comment by lewismc** [comment]
README has been updated. Please see 

```
You will now be able to access the Mudrod Web Application at http://localhost:8080/mudrod-service. N.B. The service should not be run this way in production. Please see below for running the service via Tomcat.
```
