### ISSUE TITLE
Have logging print to terminal as well as mudrod.log

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#55]
Currently the logging is configured within [log4j.properties](https://github.com/mudrod/mudrod/blob/master/core/src/main/resources/log4j.properties) we need to ensure that application output is also printed to the terminal.

**Comment by lewismc** [comment]
I've fixed this in my current additions to the temp0901 branch. I will push them shortly.

**Comment by Yongyao** [comment]
Can you push them ASAP so that we can update the user manual and associated videos.

**Comment by lewismc** [comment]
Done, you can find my most recent code within https://github.com/mudrod/mudrod/pull/59

This is also available via the spark2.0.0 branch https://github.com/mudrod/mudrod/tree/spark2.0.0

**Comment by Yongyao** [comment]
The logs are being printed out on the terminal, but there are a lot of low level logs, such as the log from elasticsearch and spark, which kind of confuses user. It would be better if we could remove them and only keep logs like "log ingest starts/ends".

![image](https://cloud.githubusercontent.com/assets/5552606/18612844/4a7a6e7a-7d33-11e6-97f1-acaae9550178.png)

**Comment by lewismc** [comment]
@Yongyao the application logs are not for users. They are for systems administrators such as you, Yun and me.
This being said, we can set custom logging levels for some packages as follows

https://github.com/mudrod/mudrod/blob/master/core/src/main/resources/log4j.properties#L76-L79

**Comment by lewismc** [comment]
This is resolved. If you want to improve logging then lets start a new issue @Yongyao
