### ISSUE TITLE
Add progress bar to individual tasks extending DiscoveryStepAbstract

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#58]
Right now, application logs just sit and wait, for quite some time... ideally we would have a command line progress bar which would indicate progress. This issue should provide this functionality for system administrators to see job progress.

**Comment by lewismc** [comment]
Possible candidate https://github.com/raszi/java-progressbar

**Comment by Yongyao** [comment]
Agree, we can definitely do this after testing.

**Comment by lewismc** [comment]
ack

**Comment by lewismc** [comment]
This issue is no longer valid, with the upgrade to Spark and Elasticsearch we get the progress bars for free.
