### ISSUE TITLE
Presentation improvements to WebUI

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#64]
Looking at the ranked query results as below

<img width="1053" alt="screen shot 2016-09-28 at 1 42 58 pm" src="https://cloud.githubusercontent.com/assets/1165719/18931679/0c74cde4-8582-11e6-97e8-859c85449dac.png">

We need to 
- choose a 'brighter' color of green... the dark green does not stuck out very well and may be difficult for some people to read.
- ensure that all columns are uniformly formatted. Right now the text seems to loop back on itself... this is untidy and can be improved.
- have an expansion button for every abstract such that users can simply click to expand the abstract text should they wish. I think that this is called 'accordion' in JQuery UI... however I may be wrong.

@quintinali can you please have a look at this as i think you are much better at UI than me?

**Comment by quintinali** [comment]
@lewismc  I will change UI colors. For metadata content, 16 attributes are listed now.

![image](https://cloud.githubusercontent.com/assets/8673393/23570530/65faedb4-0019-11e7-8b01-56c548cffa1e.png)

**Comment by lewismc** [comment]
Thank you @quintinali can you please send this to Thomas Huang and ask if he is satisfied with it?

**Comment by quintinali** [comment]
@lewismc I found that Thomas Huang needs us to add more information in the search list. What I just posted is the dataset detail page. I will add more details in the search list as PO.DAAC does and then send to him.

**Comment by lewismc** [comment]
Thank you

**Comment by quintinali** [comment]
please review this pull request, thanks. https://github.com/mudrod/mudrod/pull/108

**Comment by lewismc** [comment]
@quintinali please open a new issue for the additional elements which have to be added to each dataset results page. Thanks
