### ISSUE TITLE
SonarQube questions

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#67]
@lewismc I just installed the SonarQube plugin of eclipse. The question I have is, why am I only seeing 60 bugs on my local SQ, but there are 200+ on the remote one. Is it because different setting are used in local and remote ones? I am also trying to New a SQ server, but I don't have the information below. 
![image](https://cloud.githubusercontent.com/assets/5552606/18960370/7b2de562-8637-11e6-9430-9fae6593918e.png)

BTW, let's say I have another project, how am I supposed to connect it with SQ? Didn't find much document on this issue.
![image](https://cloud.githubusercontent.com/assets/5552606/18960218/057089b0-8637-11e6-8b10-3bace9e3431d.png)

The document I am referencing is http://www.sonarlint.org/eclipse/

**Comment by lewismc** [comment]
Hi @Yongyao thanks for trying this out. I can promise you it will make a HUGE difference.
OK so now to the questions

> The question I have is, why am I only seeing 60 bugs on my local SQ, but there are 200+ on the remote one. Is it because different setting are used in local and remote ones?

In short yes, this is exactly the reason. The online SQ server has a 'policy' setup where types of issues are flagged as bugs, other issues are flagged as code smells, etc. I wouldn't worry too much about this though. We can just work through the issues online and you will see over time the difference that we make.

> TW, let's say I have another project, how am I supposed to connect it with SQ? Didn't find much document on this issue.

Lets go through this next week at our meeting. You can then take some notes and we can put them on this project wiki or something. It takes quite a few steps (mostly configuration).

**Comment by Yongyao** [comment]
Great. Let's keep this issue open until next week.

**Comment by lewismc** [comment]
@Yongyao did you ever fix this?
