### ISSUE TITLE
Evaluate use of org.apache.commons.lang and org.apache.commons.lang3 dependencies

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#69]
In mudrod-core, we DO NOT declare but actually DO use both of the following dependencies

```
[WARNING]    commons-lang:commons-lang:jar:2.5:compile
[WARNING]    org.apache.commons:commons-lang3:jar:3.3.2:compile
```

... the issues is however that we only use one function from each dependency, and only on one occasion. We should probably try to write out own implementations and reduce the dependency usage.

```
lmcgibbn@LMC-056430 /usr/local/mudrod/core(master) $ grep -lr "org.apache.commons.lang" .
./src/main/java/esiptestbed/mudrod/driver/ESDriver.java
./src/main/java/esiptestbed/mudrod/recommendation/structure/OHCodeExtractor.java
```

**Comment by quintinali** [comment]
@lewismc OHCodeExtractor.java has been deleted. The one-hot encoder is no longer used in recommendation algorithm.

**Comment by lewismc** [comment]
If this import is no longer used in MUDROD then please close this issue out.
