### ISSUE TITLE
Ranking improvment

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#71]
This includes adding more features, code quality improvement, and so on.

**Comment by Yongyao** [comment]
Found a few links about the search in Bloomberg,

https://www.techatbloomberg.com/blog/how-bloomberg-built-a-better-search-engine-with-open-source-technology/
https://www.youtube.com/watch?v=mz41RGhDu_k 
https://berlinbuzzwords.de/sites/berlinbuzzwords.de/files/media/documents/berlin-buzzwords-news-search.pdf

**Comment by lewismc** [comment]
Work is ongoing where?
