### ISSUE TITLE
vocab.html does not render correctly

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#73]
Using master branch, when I am navigating the WebApp, I get the following... which is not right. This needs to be addressed.

<img width="1440" alt="screen shot 2016-10-11 at 1 10 11 pm" src="https://cloud.githubusercontent.com/assets/1165719/19286862/32bf3be2-8fb4-11e6-9e77-c029d494e315.png">

**Comment by Yongyao** [comment]
This html is supposed to be removed. @quintinali Can you clean up those useless code of WebUI?

**Comment by quintinali** [comment]
This html is out of date. I will clean the  useless code.  @lewismc , I want to know for this kind of modification, do I have to create a new branch and pull a request to merge modification to the master, or I can just do these modifications in the master branch?  Look forward to  your suggestions, thanks!

**Comment by lewismc** [comment]
If you could please make the changes based off of the MUDROD-66 branch that would be great.

**Comment by lewismc** [comment]
@quintinali can you check if this issue is fixed in master branch or not? Thank you

**Comment by Yongyao** [comment]
@lewismc This html should be removed, as it is not used by the current prototype anymore.

**Comment by lewismc** [comment]
commit 97d6a70a7facfe1c15b9807d4cb8ad73c6cb1eee
Author: Lewis John McGibbney <lewis.mcgibbney@gmail.com>
Date:   Thu Feb 23 09:32:43 2017 -0800

    ISSUE-73 vocab.html does not render correctly
