### ISSUE TITLE
Deploy mudrod at JPL

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#81]
Deploy an instance of mudrod running on JPL cloud hardware.

**Comment by fgreg** [comment]
Work is being done here https://github.com/fgreg/mudrod/tree/mudrod-81

**Comment by fgreg** [comment]
@lewismc Check out [my latest commit](https://github.com/fgreg/mudrod/commit/16215970c7046713aa007cec4f49254afd1f7e22) to my branch linked above. I created a new 'web' module which holds only the static resources. Essentially this turns 'service' into a REST-only web service with all of the html/js in 'web'. This will make it easier to add the JPL branding that is required on the UI.

**Comment by lewismc** [comment]
@fgreg yes much better. Much cleaner. Once your finished, please send a PR and we can merge into master. Nice work.

**Comment by fgreg** [comment]
Still working on this.

**Comment by fgreg** [comment]
This is done. Just need to ingest some data now.
