### ISSUE TITLE
Changes all packages to gov.nasa.jpl.mudrod

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#82]
ESIP has nothing to do with the project. Prior to our 1.0-release we should change the package naming and also the Maven POM definitions to the above structure.

**Comment by fgreg** [comment]
@Yongyao @lewismc @quintinali Just a heads up... once this gets merged I'd strongly recommend doing a 'clean install' from parent before trying to run the app locally again.

**Comment by lewismc** [comment]
No joke.. I think we should try to implement this just prior to next weeks meeting... we could potentially release Mudrod 0.1 around then as well.
