### ISSUE TITLE
Adapt ontology pipeline to read from PO.DAAC WebServices API

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#96]
PO.DAAC provides [WebServices](https://podaac.jpl.nasa.gov/ws) which we should use to augment the Ontologies we are creating ad hosting within the ESIP Semantic Portal.
Justification for this is that the WebServices provide us with much more information than the dataset landing pages pages. This is because the XML WebService response complies with the full GCMD-DIF XSD data model.

**Comment by Yongyao** [comment]
The metadata I sent you were exactly harvested from PO.DAAC Webservices, and we already have the harvesting code in MUDROD. https://github.com/mudrod/mudrod/blob/master/core/src/main/java/esiptestbed/mudrod/metadata/pre/ApiHarvester.java#L132

**Comment by lewismc** [comment]
Thanks @Yongyao

**Comment by lewismc** [comment]
Implemented in https://github.com/ESIPFed/eskg/issues/14
