### ISSUE TITLE
Failed to see the search results in the web UI

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#98]
@lewismc , sorry for not doing this earlier. Below is the bug report,

Environment:
Mac, eclipse, tomcat 8, chrome

Steps to reproduce:
1. Run the mudrod-core with "-p"
2. Start the mudrod-service in eclipse with tomcat
3. After you see the landing page, type in "ocean wind"

Expected result:
A list of search results

Actual result:
nothing (always loading...)

I can see the search results printed in the console of eclipse,

`2017-03-01 21:51:14,608 INFO  search.SearchMetadataResource (SearchMetadataResource.java:searchMetadata(76)) - Response received: "{\"PDResults\":[{\"Short Name\":\"SPURS1_DRIFTER\",\"Long Name\":\"Drifter data for the SPURS-1 N. Atlantic field campaign\",\"Topic\":\"Temperature Profiles, Salini...`

However, I found an error on the browser,

<img width="543" alt="screen shot 2017-03-01 at 9 53 18 pm" src="https://cloud.githubusercontent.com/assets/5552606/23490977/a45bfe96-fec9-11e6-8601-a7053fabce6f.png">

**Comment by fgreg** [comment]
@Yongyao this should be fixed with https://github.com/mudrod/mudrod/pull/99

Please check.
